#include "util.h"
#include <string>
#include <array>

extern const std::array<std::string, 441> pokemon_name_list = {
"?",
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran♀",
"Nidorina",
"Nidoqueen",
"Nidoran♂",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch'd",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr.",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"Chikorita",
"Bayleef",
"Meganium",
"Cyndaquil",
"Quilava",
"Typhlosion",
"Totodile",
"Croconaw",
"Feraligatr",
"Sentret",
"Furret",
"Hoothoot",
"Noctowl",
"Ledyba",
"Ledian",
"Spinarak",
"Ariados",
"Crobat",
"Chinchou",
"Lanturn",
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Togetic",
"Natu",
"Xatu",
"Mareep",
"Flaaffy",
"Ampharos",
"Bellossom",
"Marill",
"Azumarill",
"Sudowoodo",
"Politoed",
"Hoppip",
"Skiploom",
"Jumpluff",
"Aipom",
"Sunkern",
"Sunflora",
"Yanma",
"Wooper",
"Quagsire",
"Espeon",
"Umbreon",
"Murkrow",
"Slowking",
"Misdreavus",
"Unown",
"Wobbuffet",
"Girafarig",
"Pineco",
"Forretress",
"Dunsparce",
"Gligar",
"Steelix",
"Snubbull",
"Granbull",
"Qwilfish",
"Scizor",
"Shuckle",
"Heracross",
"Sneasel",
"Teddiursa",
"Ursaring",
"Slugma",
"Magcargo",
"Swinub",
"Piloswine",
"Corsola",
"Remoraid",
"Octillery",
"Delibird",
"Mantine",
"Skarmory",
"Houndour",
"Houndoom",
"Kingdra",
"Phanpy",
"Donphan",
"Porygon2",
"Stantler",
"Smeargle",
"Tyrogue",
"Hitmontop",
"Smoochum",
"Elekid",
"Magby",
"Miltank",
"Blissey",
"Raikou",
"Entei",
"Suicune",
"Larvitar",
"Pupitar",
"Tyranitar",
"Lugia",
"Ho-Oh",
"Celebi",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"Treecko",
"Grovyle",
"Sceptile",
"Torchic",
"Combusken",
"Blaziken",
"Mudkip",
"Marshtomp",
"Swampert",
"Poochyena",
"Mightyena",
"Zigzagoon",
"Linoone",
"Wurmple",
"Silcoon",
"Beautifly",
"Cascoon",
"Dustox",
"Lotad",
"Lombre",
"Ludicolo",
"Seedot",
"Nuzleaf",
"Shiftry",
"Nincada",
"Ninjask",
"Shedinja",
"Taillow",
"Swellow",
"Shroomish",
"Breloom",
"Spinda",
"Wingull",
"Pelipper",
"Surskit",
"Masquerain",
"Wailmer",
"Wailord",
"Skitty",
"Delcatty",
"Kecleon",
"Baltoy",
"Claydol",
"Nosepass",
"Torkoal",
"Sableye",
"Barboach",
"Whiscash",
"Luvdisc",
"Corphish",
"Crawdaunt",
"Feebas",
"Milotic",
"Carvanha",
"Sharpedo",
"Trapinch",
"Vibrava",
"Flygon",
"Makuhita",
"Hariyama",
"Electrike",
"Manectric",
"Numel",
"Camerupt",
"Spheal",
"Sealeo",
"Walrein",
"Cacnea",
"Cacturne",
"Snorunt",
"Glalie",
"Lunatone",
"Solrock",
"Azurill",
"Spoink",
"Grumpig",
"Plusle",
"Minun",
"Mawile",
"Meditite",
"Medicham",
"Swablu",
"Altaria",
"Wynaut",
"Duskull",
"Dusclops",
"Roselia",
"Slakoth",
"Vigoroth",
"Slaking",
"Gulpin",
"Swalot",
"Tropius",
"Whismur",
"Loudred",
"Exploud",
"Clamperl",
"Huntail",
"Gorebyss",
"Absol",
"Shuppet",
"Banette",
"Seviper",
"Zangoose",
"Relicanth",
"Aron",
"Lairon",
"Aggron",
"Castform",
"Volbeat",
"Illumise",
"Lileep",
"Cradily",
"Anorith",
"Armaldo",
"Ralts",
"Kirlia",
"Gardevoir",
"Bagon",
"Shelgon",
"Salamence",
"Beldum",
"Metang",
"Metagross",
"Regirock",
"Regice",
"Registeel",
"Kyogre",
"Groudon",
"Rayquaza",
"Latias",
"Latios",
"Jirachi",
"Deoxys",
"Chimecho",
"Pokémon",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"?",
};

extern const std::array<struct rs_item, 349> items_names_list = {
 rs_item{ .name = "Nothing", .bag_category = BAD_CATEGORY, .id = 0x0, .quantity = 0 },
 rs_item{ .name = "Master Ball", .bag_category = BALL_CATEGORY, .id = 0x1, .quantity = 0 },
 rs_item{ .name = "Ultra Ball", .bag_category = BALL_CATEGORY, .id = 0x2, .quantity = 0 },
 rs_item{ .name = "Great Ball", .bag_category = BALL_CATEGORY, .id = 0x3, .quantity = 0 },
 rs_item{ .name = "Poké Ball", .bag_category = BALL_CATEGORY, .id = 0x4, .quantity = 0 },
 rs_item{ .name = "Safari Ball", .bag_category = BALL_CATEGORY, .id = 0x5, .quantity = 0 },
 rs_item{ .name = "Net Ball", .bag_category = BALL_CATEGORY, .id = 0x6, .quantity = 0 },
 rs_item{ .name = "Dive Ball", .bag_category = BALL_CATEGORY, .id = 0x7, .quantity = 0 },
 rs_item{ .name = "Nest Ball", .bag_category = BALL_CATEGORY, .id = 0x8, .quantity = 0 },
 rs_item{ .name = "Repeat Ball", .bag_category = BALL_CATEGORY, .id = 0x9, .quantity = 0 },
 rs_item{ .name = "Timer Ball", .bag_category = BALL_CATEGORY, .id = 0xa, .quantity = 0 },
 rs_item{ .name = "Luxury Ball", .bag_category = BALL_CATEGORY, .id = 0xb, .quantity = 0 },
 rs_item{ .name = "Premier Ball", .bag_category = BALL_CATEGORY, .id = 0xc, .quantity = 0 },
 rs_item{ .name = "Potion", .bag_category = ITEM_CATEGORY, .id = 0xd, .quantity = 0 },
 rs_item{ .name = "Antidote", .bag_category = ITEM_CATEGORY, .id = 0xe, .quantity = 0 },
 rs_item{ .name = "Burn Heal", .bag_category = ITEM_CATEGORY, .id = 0xf, .quantity = 0 },
 rs_item{ .name = "Ice Heal", .bag_category = ITEM_CATEGORY, .id = 0x10, .quantity = 0 },
 rs_item{ .name = "Awakening", .bag_category = ITEM_CATEGORY, .id = 0x11, .quantity = 0 },
 rs_item{ .name = "Parlyz Heal", .bag_category = ITEM_CATEGORY, .id = 0x12, .quantity = 0 },
 rs_item{ .name = "Full Restore", .bag_category = ITEM_CATEGORY, .id = 0x13, .quantity = 0 },
 rs_item{ .name = "Max Potion", .bag_category = ITEM_CATEGORY, .id = 0x14, .quantity = 0 },
 rs_item{ .name = "Hyper Potion", .bag_category = ITEM_CATEGORY, .id = 0x15, .quantity = 0 },
 rs_item{ .name = "Super Potion", .bag_category = ITEM_CATEGORY, .id = 0x16, .quantity = 0 },
 rs_item{ .name = "Full Heal", .bag_category = ITEM_CATEGORY, .id = 0x17, .quantity = 0 },
 rs_item{ .name = "Revive", .bag_category = ITEM_CATEGORY, .id = 0x18, .quantity = 0 },
 rs_item{ .name = "Max Revive", .bag_category = ITEM_CATEGORY, .id = 0x19, .quantity = 0 },
 rs_item{ .name = "Fresh Water", .bag_category = ITEM_CATEGORY, .id = 0x1a, .quantity = 0 },
 rs_item{ .name = "Soda Pop", .bag_category = ITEM_CATEGORY, .id = 0x1b, .quantity = 0 },
 rs_item{ .name = "Lemonade", .bag_category = ITEM_CATEGORY, .id = 0x1c, .quantity = 0 },
 rs_item{ .name = "Moomoo Milk", .bag_category = ITEM_CATEGORY, .id = 0x1d, .quantity = 0 },
 rs_item{ .name = "EnergyPowder", .bag_category = ITEM_CATEGORY, .id = 0x1e, .quantity = 0 },
 rs_item{ .name = "Energy Root", .bag_category = ITEM_CATEGORY, .id = 0x1f, .quantity = 0 },
 rs_item{ .name = "Heal Powder", .bag_category = ITEM_CATEGORY, .id = 0x20, .quantity = 0 },
 rs_item{ .name = "Revival Herb", .bag_category = ITEM_CATEGORY, .id = 0x21, .quantity = 0 },
 rs_item{ .name = "Ether", .bag_category = ITEM_CATEGORY, .id = 0x22, .quantity = 0 },
 rs_item{ .name = "Max Ether", .bag_category = ITEM_CATEGORY, .id = 0x23, .quantity = 0 },
 rs_item{ .name = "Elixir", .bag_category = ITEM_CATEGORY, .id = 0x24, .quantity = 0 },
 rs_item{ .name = "Max Elixir", .bag_category = ITEM_CATEGORY, .id = 0x25, .quantity = 0 },
 rs_item{ .name = "Lava Cookie", .bag_category = ITEM_CATEGORY, .id = 0x26, .quantity = 0 },
 rs_item{ .name = "Blue Flute", .bag_category = ITEM_CATEGORY, .id = 0x27, .quantity = 0 },
 rs_item{ .name = "Yellow Flute", .bag_category = ITEM_CATEGORY, .id = 0x28, .quantity = 0 },
 rs_item{ .name = "Red Flute", .bag_category = ITEM_CATEGORY, .id = 0x29, .quantity = 0 },
 rs_item{ .name = "Black Flute", .bag_category = ITEM_CATEGORY, .id = 0x2a, .quantity = 0 },
 rs_item{ .name = "White Flute", .bag_category = ITEM_CATEGORY, .id = 0x2b, .quantity = 0 },
 rs_item{ .name = "Berry Juice", .bag_category = ITEM_CATEGORY, .id = 0x2c, .quantity = 0 },
 rs_item{ .name = "Sacred Ash", .bag_category = ITEM_CATEGORY, .id = 0x2d, .quantity = 0 },
 rs_item{ .name = "Shoal Salt", .bag_category = ITEM_CATEGORY, .id = 0x2e, .quantity = 0 },
 rs_item{ .name = "Shoal Shell", .bag_category = ITEM_CATEGORY, .id = 0x2f, .quantity = 0 },
 rs_item{ .name = "Red Shard", .bag_category = ITEM_CATEGORY, .id = 0x30, .quantity = 0 },
 rs_item{ .name = "Blue Shard", .bag_category = ITEM_CATEGORY, .id = 0x31, .quantity = 0 },
 rs_item{ .name = "Yellow Shard", .bag_category = ITEM_CATEGORY, .id = 0x32, .quantity = 0 },
 rs_item{ .name = "Green Shard", .bag_category = ITEM_CATEGORY, .id = 0x33, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x34, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x35, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x36, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x37, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x38, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x39, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3a, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3b, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3c, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3d, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3e, .quantity = 0 },
 rs_item{ .name = "HP Up", .bag_category = ITEM_CATEGORY, .id = 0x3f, .quantity = 0 },
 rs_item{ .name = "Protein", .bag_category = ITEM_CATEGORY, .id = 0x40, .quantity = 0 },
 rs_item{ .name = "Iron", .bag_category = ITEM_CATEGORY, .id = 0x41, .quantity = 0 },
 rs_item{ .name = "Carbos", .bag_category = ITEM_CATEGORY, .id = 0x42, .quantity = 0 },
 rs_item{ .name = "Calcium", .bag_category = ITEM_CATEGORY, .id = 0x43, .quantity = 0 },
 rs_item{ .name = "Rare Candy", .bag_category = ITEM_CATEGORY, .id = 0x44, .quantity = 0 },
 rs_item{ .name = "PP Up", .bag_category = ITEM_CATEGORY, .id = 0x45, .quantity = 0 },
 rs_item{ .name = "Zinc", .bag_category = ITEM_CATEGORY, .id = 0x46, .quantity = 0 },
 rs_item{ .name = "PP Max", .bag_category = ITEM_CATEGORY, .id = 0x47, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = ITEM_CATEGORY, .id = 0x48, .quantity = 0 },
 rs_item{ .name = "Guard Spec.", .bag_category = ITEM_CATEGORY, .id = 0x49, .quantity = 0 },
 rs_item{ .name = "Dire Hit", .bag_category = ITEM_CATEGORY, .id = 0x4a, .quantity = 0 },
 rs_item{ .name = "X Attack", .bag_category = ITEM_CATEGORY, .id = 0x4b, .quantity = 0 },
 rs_item{ .name = "X Defend", .bag_category = ITEM_CATEGORY, .id = 0x4c, .quantity = 0 },
 rs_item{ .name = "X Speed", .bag_category = ITEM_CATEGORY, .id = 0x4d, .quantity = 0 },
 rs_item{ .name = "X Accuracy", .bag_category = ITEM_CATEGORY, .id = 0x4e, .quantity = 0 },
 rs_item{ .name = "X Special", .bag_category = ITEM_CATEGORY, .id = 0x4f, .quantity = 0 },
 rs_item{ .name = "Poké Doll", .bag_category = ITEM_CATEGORY, .id = 0x50, .quantity = 0 },
 rs_item{ .name = "Fluffy Tail", .bag_category = ITEM_CATEGORY, .id = 0x51, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = ITEM_CATEGORY, .id = 0x52, .quantity = 0 },
 rs_item{ .name = "Super Repel", .bag_category = ITEM_CATEGORY, .id = 0x53, .quantity = 0 },
 rs_item{ .name = "Max Repel", .bag_category = ITEM_CATEGORY, .id = 0x54, .quantity = 0 },
 rs_item{ .name = "Escape Rope", .bag_category = ITEM_CATEGORY, .id = 0x55, .quantity = 0 },
 rs_item{ .name = "Repel", .bag_category = ITEM_CATEGORY, .id = 0x56, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x57, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x58, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x59, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x5a, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x5b, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x5c, .quantity = 0 },
 rs_item{ .name = "Sun Stone", .bag_category = ITEM_CATEGORY, .id = 0x5d, .quantity = 0 },
 rs_item{ .name = "Moon Stone", .bag_category = ITEM_CATEGORY, .id = 0x5e, .quantity = 0 },
 rs_item{ .name = "Fire Stone", .bag_category = ITEM_CATEGORY, .id = 0x5f, .quantity = 0 },
 rs_item{ .name = "Thunderstone", .bag_category = ITEM_CATEGORY, .id = 0x60, .quantity = 0 },
 rs_item{ .name = "Water Stone", .bag_category = ITEM_CATEGORY, .id = 0x61, .quantity = 0 },
 rs_item{ .name = "Leaf Stone", .bag_category = ITEM_CATEGORY, .id = 0x62, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x63, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x64, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x65, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x66, .quantity = 0 },
 rs_item{ .name = "TinyMushroom", .bag_category = ITEM_CATEGORY, .id = 0x67, .quantity = 0 },
 rs_item{ .name = "Big Mushroom", .bag_category = ITEM_CATEGORY, .id = 0x68, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = ITEM_CATEGORY, .id = 0x69, .quantity = 0 },
 rs_item{ .name = "Pearl", .bag_category = ITEM_CATEGORY, .id = 0x6a, .quantity = 0 },
 rs_item{ .name = "Big Pearl", .bag_category = ITEM_CATEGORY, .id = 0x6b, .quantity = 0 },
 rs_item{ .name = "Stardust", .bag_category = ITEM_CATEGORY, .id = 0x6c, .quantity = 0 },
 rs_item{ .name = "Star Piece", .bag_category = ITEM_CATEGORY, .id = 0x6d, .quantity = 0 },
 rs_item{ .name = "Nugget", .bag_category = ITEM_CATEGORY, .id = 0x6e, .quantity = 0 },
 rs_item{ .name = "Heart Scale", .bag_category = ITEM_CATEGORY, .id = 0x6f, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x70, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x71, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x72, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x73, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x74, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x75, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x76, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x77, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x78, .quantity = 0 },
 rs_item{ .name = "Orange Mail", .bag_category = ITEM_CATEGORY, .id = 0x79, .quantity = 0 },
 rs_item{ .name = "Harbor Mail", .bag_category = ITEM_CATEGORY, .id = 0x7a, .quantity = 0 },
 rs_item{ .name = "Glitter Mail", .bag_category = ITEM_CATEGORY, .id = 0x7b, .quantity = 0 },
 rs_item{ .name = "Mech Mail", .bag_category = ITEM_CATEGORY, .id = 0x7c, .quantity = 0 },
 rs_item{ .name = "Wood Mail", .bag_category = ITEM_CATEGORY, .id = 0x7d, .quantity = 0 },
 rs_item{ .name = "Wave Mail", .bag_category = ITEM_CATEGORY, .id = 0x7e, .quantity = 0 },
 rs_item{ .name = "Bead Mail", .bag_category = ITEM_CATEGORY, .id = 0x7f, .quantity = 0 },
 rs_item{ .name = "Shadow Mail", .bag_category = ITEM_CATEGORY, .id = 0x80, .quantity = 0 },
 rs_item{ .name = "Tropic Mail", .bag_category = ITEM_CATEGORY, .id = 0x81, .quantity = 0 },
 rs_item{ .name = "Dream Mail", .bag_category = ITEM_CATEGORY, .id = 0x82, .quantity = 0 },
 rs_item{ .name = "Fab Mail", .bag_category = ITEM_CATEGORY, .id = 0x83, .quantity = 0 },
 rs_item{ .name = "Retro Mail", .bag_category = ITEM_CATEGORY, .id = 0x84, .quantity = 0 },
 rs_item{ .name = "Cheri Berry", .bag_category = BERRY_CATEGORY, .id = 0x85, .quantity = 0 },
 rs_item{ .name = "Chesto Berry", .bag_category = BERRY_CATEGORY, .id = 0x86, .quantity = 0 },
 rs_item{ .name = "Pecha Berry", .bag_category = BERRY_CATEGORY, .id = 0x87, .quantity = 0 },
 rs_item{ .name = "Rawst Berry", .bag_category = BERRY_CATEGORY, .id = 0x88, .quantity = 0 },
 rs_item{ .name = "Aspear Berry", .bag_category = BERRY_CATEGORY, .id = 0x89, .quantity = 0 },
 rs_item{ .name = "Leppa Berry", .bag_category = BERRY_CATEGORY, .id = 0x8a, .quantity = 0 },
 rs_item{ .name = "Oran Berry", .bag_category = BERRY_CATEGORY, .id = 0x8b, .quantity = 0 },
 rs_item{ .name = "Persim Berry", .bag_category = BERRY_CATEGORY, .id = 0x8c, .quantity = 0 },
 rs_item{ .name = "Lum Berry", .bag_category = BERRY_CATEGORY, .id = 0x8d, .quantity = 0 },
 rs_item{ .name = "Sitrus Berry", .bag_category = BERRY_CATEGORY, .id = 0x8e, .quantity = 0 },
 rs_item{ .name = "Figy Berry", .bag_category = BERRY_CATEGORY, .id = 0x8f, .quantity = 0 },
 rs_item{ .name = "Wiki Berry", .bag_category = BERRY_CATEGORY, .id = 0x90, .quantity = 0 },
 rs_item{ .name = "Mago Berry", .bag_category = BERRY_CATEGORY, .id = 0x91, .quantity = 0 },
 rs_item{ .name = "Aguav Berry", .bag_category = BERRY_CATEGORY, .id = 0x92, .quantity = 0 },
 rs_item{ .name = "Iapapa Berry", .bag_category = BERRY_CATEGORY, .id = 0x93, .quantity = 0 },
 rs_item{ .name = "Razz Berry", .bag_category = BERRY_CATEGORY, .id = 0x94, .quantity = 0 },
 rs_item{ .name = "Bluk Berry", .bag_category = BERRY_CATEGORY, .id = 0x95, .quantity = 0 },
 rs_item{ .name = "Nanab Berry", .bag_category = BERRY_CATEGORY, .id = 0x96, .quantity = 0 },
 rs_item{ .name = "Wepear Berry", .bag_category = BERRY_CATEGORY, .id = 0x97, .quantity = 0 },
 rs_item{ .name = "Pinap Berry", .bag_category = BERRY_CATEGORY, .id = 0x98, .quantity = 0 },
 rs_item{ .name = "Pomeg Berry", .bag_category = BERRY_CATEGORY, .id = 0x99, .quantity = 0 },
 rs_item{ .name = "Kelpsy Berry", .bag_category = BERRY_CATEGORY, .id = 0x9a, .quantity = 0 },
 rs_item{ .name = "Qualot Berry", .bag_category = BERRY_CATEGORY, .id = 0x9b, .quantity = 0 },
 rs_item{ .name = "Hondew Berry", .bag_category = BERRY_CATEGORY, .id = 0x9c, .quantity = 0 },
 rs_item{ .name = "Grepa Berry", .bag_category = BERRY_CATEGORY, .id = 0x9d, .quantity = 0 },
 rs_item{ .name = "Tamato Berry", .bag_category = BERRY_CATEGORY, .id = 0x9e, .quantity = 0 },
 rs_item{ .name = "Cornn Berry", .bag_category = BERRY_CATEGORY, .id = 0x9f, .quantity = 0 },
 rs_item{ .name = "Magost Berry", .bag_category = BERRY_CATEGORY, .id = 0xa0, .quantity = 0 },
 rs_item{ .name = "Rabuta Berry", .bag_category = BERRY_CATEGORY, .id = 0xa1, .quantity = 0 },
 rs_item{ .name = "Nomel Berry", .bag_category = BERRY_CATEGORY, .id = 0xa2, .quantity = 0 },
 rs_item{ .name = "Spelon Berry", .bag_category = BERRY_CATEGORY, .id = 0xa3, .quantity = 0 },
 rs_item{ .name = "Pamtre Berry", .bag_category = BERRY_CATEGORY, .id = 0xa4, .quantity = 0 },
 rs_item{ .name = "Watmel Berry", .bag_category = BERRY_CATEGORY, .id = 0xa5, .quantity = 0 },
 rs_item{ .name = "Durin Berry", .bag_category = BERRY_CATEGORY, .id = 0xa6, .quantity = 0 },
 rs_item{ .name = "Belue Berry", .bag_category = BERRY_CATEGORY, .id = 0xa7, .quantity = 0 },
 rs_item{ .name = "Liechi Berry", .bag_category = BERRY_CATEGORY, .id = 0xa8, .quantity = 0 },
 rs_item{ .name = "Ganlon Berry", .bag_category = BERRY_CATEGORY, .id = 0xa9, .quantity = 0 },
 rs_item{ .name = "Salac Berry", .bag_category = BERRY_CATEGORY, .id = 0xaa, .quantity = 0 },
 rs_item{ .name = "Petaya Berry", .bag_category = BERRY_CATEGORY, .id = 0xab, .quantity = 0 },
 rs_item{ .name = "Apicot Berry", .bag_category = BERRY_CATEGORY, .id = 0xac, .quantity = 0 },
 rs_item{ .name = "Lansat Berry", .bag_category = BERRY_CATEGORY, .id = 0xad, .quantity = 0 },
 rs_item{ .name = "Starf Berry", .bag_category = BERRY_CATEGORY, .id = 0xae, .quantity = 0 },
 rs_item{ .name = "Enigma Berry", .bag_category = BERRY_CATEGORY, .id = 0xaf, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xb0, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xb1, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xb2, .quantity = 0 },
 rs_item{ .name = "BrightPowder", .bag_category = ITEM_CATEGORY, .id = 0xb3, .quantity = 0 },
 rs_item{ .name = "White Herb", .bag_category = ITEM_CATEGORY, .id = 0xb4, .quantity = 0 },
 rs_item{ .name = "Macho Brace", .bag_category = ITEM_CATEGORY, .id = 0xb5, .quantity = 0 },
 rs_item{ .name = "Exp. Share", .bag_category = ITEM_CATEGORY, .id = 0xb6, .quantity = 0 },
 rs_item{ .name = "Quick Claw", .bag_category = ITEM_CATEGORY, .id = 0xb7, .quantity = 0 },
 rs_item{ .name = "Soothe Bell", .bag_category = ITEM_CATEGORY, .id = 0xb8, .quantity = 0 },
 rs_item{ .name = "Mental Herb", .bag_category = ITEM_CATEGORY, .id = 0xb9, .quantity = 0 },
 rs_item{ .name = "Choice Band", .bag_category = ITEM_CATEGORY, .id = 0xba, .quantity = 0 },
 rs_item{ .name = "King's Rock", .bag_category = ITEM_CATEGORY, .id = 0xbb, .quantity = 0 },
 rs_item{ .name = "SilverPowder", .bag_category = ITEM_CATEGORY, .id = 0xbc, .quantity = 0 },
 rs_item{ .name = "Amulet Coin", .bag_category = ITEM_CATEGORY, .id = 0xbd, .quantity = 0 },
 rs_item{ .name = "Cleanse Tag", .bag_category = ITEM_CATEGORY, .id = 0xbe, .quantity = 0 },
 rs_item{ .name = "Soul Dew", .bag_category = ITEM_CATEGORY, .id = 0xbf, .quantity = 0 },
 rs_item{ .name = "DeepSeaTooth", .bag_category = ITEM_CATEGORY, .id = 0xc0, .quantity = 0 },
 rs_item{ .name = "DeepSeaScale", .bag_category = ITEM_CATEGORY, .id = 0xc1, .quantity = 0 },
 rs_item{ .name = "Smoke Ball", .bag_category = ITEM_CATEGORY, .id = 0xc2, .quantity = 0 },
 rs_item{ .name = "Everstone", .bag_category = ITEM_CATEGORY, .id = 0xc3, .quantity = 0 },
 rs_item{ .name = "Focus Band", .bag_category = ITEM_CATEGORY, .id = 0xc4, .quantity = 0 },
 rs_item{ .name = "Lucky Egg", .bag_category = ITEM_CATEGORY, .id = 0xc5, .quantity = 0 },
 rs_item{ .name = "Scope Lens", .bag_category = ITEM_CATEGORY, .id = 0xc6, .quantity = 0 },
 rs_item{ .name = "Metal Coat", .bag_category = ITEM_CATEGORY, .id = 0xc7, .quantity = 0 },
 rs_item{ .name = "Leftovers", .bag_category = ITEM_CATEGORY, .id = 0xc8, .quantity = 0 },
 rs_item{ .name = "Dragon Scale", .bag_category = ITEM_CATEGORY, .id = 0xc9, .quantity = 0 },
 rs_item{ .name = "Light Ball", .bag_category = ITEM_CATEGORY, .id = 0xca, .quantity = 0 },
 rs_item{ .name = "Soft Sand", .bag_category = ITEM_CATEGORY, .id = 0xcb, .quantity = 0 },
 rs_item{ .name = "Hard Stone", .bag_category = ITEM_CATEGORY, .id = 0xcc, .quantity = 0 },
 rs_item{ .name = "Miracle Seed", .bag_category = ITEM_CATEGORY, .id = 0xcd, .quantity = 0 },
 rs_item{ .name = "BlackGlasses", .bag_category = ITEM_CATEGORY, .id = 0xce, .quantity = 0 },
 rs_item{ .name = "Black Belt", .bag_category = ITEM_CATEGORY, .id = 0xcf, .quantity = 0 },
 rs_item{ .name = "Magnet", .bag_category = ITEM_CATEGORY, .id = 0xd0, .quantity = 0 },
 rs_item{ .name = "Mystic Water", .bag_category = ITEM_CATEGORY, .id = 0xd1, .quantity = 0 },
 rs_item{ .name = "Sharp Beak", .bag_category = ITEM_CATEGORY, .id = 0xd2, .quantity = 0 },
 rs_item{ .name = "Poison Barb", .bag_category = ITEM_CATEGORY, .id = 0xd3, .quantity = 0 },
 rs_item{ .name = "NeverMeltIce", .bag_category = ITEM_CATEGORY, .id = 0xd4, .quantity = 0 },
 rs_item{ .name = "Spell Tag", .bag_category = ITEM_CATEGORY, .id = 0xd5, .quantity = 0 },
 rs_item{ .name = "TwistedSpoon", .bag_category = ITEM_CATEGORY, .id = 0xd6, .quantity = 0 },
 rs_item{ .name = "Charcoal", .bag_category = ITEM_CATEGORY, .id = 0xd7, .quantity = 0 },
 rs_item{ .name = "Dragon Fang", .bag_category = ITEM_CATEGORY, .id = 0xd8, .quantity = 0 },
 rs_item{ .name = "Silk Scarf", .bag_category = ITEM_CATEGORY, .id = 0xd9, .quantity = 0 },
 rs_item{ .name = "Up-Grade", .bag_category = ITEM_CATEGORY, .id = 0xda, .quantity = 0 },
 rs_item{ .name = "Shell Bell", .bag_category = ITEM_CATEGORY, .id = 0xdb, .quantity = 0 },
 rs_item{ .name = "Sea Incense", .bag_category = ITEM_CATEGORY, .id = 0xdc, .quantity = 0 },
 rs_item{ .name = "Lax Incense", .bag_category = ITEM_CATEGORY, .id = 0xdd, .quantity = 0 },
 rs_item{ .name = "Lucky Punch", .bag_category = ITEM_CATEGORY, .id = 0xde, .quantity = 0 },
 rs_item{ .name = "Metal Powder", .bag_category = ITEM_CATEGORY, .id = 0xdf, .quantity = 0 },
 rs_item{ .name = "Thick Club", .bag_category = ITEM_CATEGORY, .id = 0xe0, .quantity = 0 },
 rs_item{ .name = "Stick", .bag_category = ITEM_CATEGORY, .id = 0xe1, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe2, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe3, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe4, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe5, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe6, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe7, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe8, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe9, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xea, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xeb, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xec, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xed, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xee, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xef, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf0, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf1, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf2, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf3, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf4, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf5, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf6, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf7, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf8, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf9, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfa, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfb, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfc, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfd, .quantity = 0 },
 rs_item{ .name = "Red Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0xfe, .quantity = 0 },
 rs_item{ .name = "Blue Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0xff, .quantity = 0 },
 rs_item{ .name = "Pink Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0x100, .quantity = 0 },
 rs_item{ .name = "Green Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0x101, .quantity = 0 },
 rs_item{ .name = "Yellow Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0x102, .quantity = 0 },
 rs_item{ .name = "Mach Bike", .bag_category = KEY_ITEM_CATEGORY, .id = 0x103, .quantity = 0 },
 rs_item{ .name = "Coin Case", .bag_category = KEY_ITEM_CATEGORY, .id = 0x104, .quantity = 0 },
 rs_item{ .name = "Itemfinder", .bag_category = KEY_ITEM_CATEGORY, .id = 0x105, .quantity = 0 },
 rs_item{ .name = "Old Rod", .bag_category = KEY_ITEM_CATEGORY, .id = 0x106, .quantity = 0 },
 rs_item{ .name = "Good Rod", .bag_category = KEY_ITEM_CATEGORY, .id = 0x107, .quantity = 0 },
 rs_item{ .name = "Super Rod", .bag_category = KEY_ITEM_CATEGORY, .id = 0x108, .quantity = 0 },
 rs_item{ .name = "S.S. Ticket", .bag_category = KEY_ITEM_CATEGORY, .id = 0x109, .quantity = 0 },
 rs_item{ .name = "Contest Pass", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10a, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10b, .quantity = 0 },
 rs_item{ .name = "Wailmer Pail", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10c, .quantity = 0 },
 rs_item{ .name = "Devon Goods", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10d, .quantity = 0 },
 rs_item{ .name = "Soot Sack", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10e, .quantity = 0 },
 rs_item{ .name = "Basement Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10f, .quantity = 0 },
 rs_item{ .name = "Acro Bike", .bag_category = KEY_ITEM_CATEGORY, .id = 0x110, .quantity = 0 },
 rs_item{ .name = "Pokéblock Case", .bag_category = KEY_ITEM_CATEGORY, .id = 0x111, .quantity = 0 },
 rs_item{ .name = "Letter", .bag_category = KEY_ITEM_CATEGORY, .id = 0x112, .quantity = 0 },
 rs_item{ .name = "Eon Ticket", .bag_category = KEY_ITEM_CATEGORY, .id = 0x113, .quantity = 0 },
 rs_item{ .name = "Red Orb", .bag_category = KEY_ITEM_CATEGORY, .id = 0x114, .quantity = 0 },
 rs_item{ .name = "Blue Orb", .bag_category = KEY_ITEM_CATEGORY, .id = 0x115, .quantity = 0 },
 rs_item{ .name = "Scanner", .bag_category = KEY_ITEM_CATEGORY, .id = 0x116, .quantity = 0 },
 rs_item{ .name = "Go-Goggles", .bag_category = KEY_ITEM_CATEGORY, .id = 0x117, .quantity = 0 },
 rs_item{ .name = "Meteorite", .bag_category = KEY_ITEM_CATEGORY, .id = 0x118, .quantity = 0 },
 rs_item{ .name = "Rm. 1 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x119, .quantity = 0 },
 rs_item{ .name = "Rm. 2 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11a, .quantity = 0 },
 rs_item{ .name = "Rm. 4 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11b, .quantity = 0 },
 rs_item{ .name = "Rm. 6 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11c, .quantity = 0 },
 rs_item{ .name = "Storage Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11d, .quantity = 0 },
 rs_item{ .name = "Root Fossil", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11e, .quantity = 0 },
 rs_item{ .name = "Claw Fossil", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11f, .quantity = 0 },
 rs_item{ .name = "Devon Scope", .bag_category = KEY_ITEM_CATEGORY, .id = 0x120, .quantity = 0 },
 rs_item{ .name = "TM01", .bag_category = TM_CATEGORY, .id = 0x121, .quantity = 0 },
 rs_item{ .name = "TM02", .bag_category = TM_CATEGORY, .id = 0x122, .quantity = 0 },
 rs_item{ .name = "TM03", .bag_category = TM_CATEGORY, .id = 0x123, .quantity = 0 },
 rs_item{ .name = "TM04", .bag_category = TM_CATEGORY, .id = 0x124, .quantity = 0 },
 rs_item{ .name = "TM05", .bag_category = TM_CATEGORY, .id = 0x125, .quantity = 0 },
 rs_item{ .name = "TM06", .bag_category = TM_CATEGORY, .id = 0x126, .quantity = 0 },
 rs_item{ .name = "TM07", .bag_category = TM_CATEGORY, .id = 0x127, .quantity = 0 },
 rs_item{ .name = "TM08", .bag_category = TM_CATEGORY, .id = 0x128, .quantity = 0 },
 rs_item{ .name = "TM09", .bag_category = TM_CATEGORY, .id = 0x129, .quantity = 0 },
 rs_item{ .name = "TM10", .bag_category = TM_CATEGORY, .id = 0x12a, .quantity = 0 },
 rs_item{ .name = "TM11", .bag_category = TM_CATEGORY, .id = 0x12b, .quantity = 0 },
 rs_item{ .name = "TM12", .bag_category = TM_CATEGORY, .id = 0x12c, .quantity = 0 },
 rs_item{ .name = "TM13", .bag_category = TM_CATEGORY, .id = 0x12d, .quantity = 0 },
 rs_item{ .name = "TM14", .bag_category = TM_CATEGORY, .id = 0x12e, .quantity = 0 },
 rs_item{ .name = "TM15", .bag_category = TM_CATEGORY, .id = 0x12f, .quantity = 0 },
 rs_item{ .name = "TM16", .bag_category = TM_CATEGORY, .id = 0x130, .quantity = 0 },
 rs_item{ .name = "TM17", .bag_category = TM_CATEGORY, .id = 0x131, .quantity = 0 },
 rs_item{ .name = "TM18", .bag_category = TM_CATEGORY, .id = 0x132, .quantity = 0 },
 rs_item{ .name = "TM19", .bag_category = TM_CATEGORY, .id = 0x133, .quantity = 0 },
 rs_item{ .name = "TM20", .bag_category = TM_CATEGORY, .id = 0x134, .quantity = 0 },
 rs_item{ .name = "TM21", .bag_category = TM_CATEGORY, .id = 0x135, .quantity = 0 },
 rs_item{ .name = "TM22", .bag_category = TM_CATEGORY, .id = 0x136, .quantity = 0 },
 rs_item{ .name = "TM23", .bag_category = TM_CATEGORY, .id = 0x137, .quantity = 0 },
 rs_item{ .name = "TM24", .bag_category = TM_CATEGORY, .id = 0x138, .quantity = 0 },
 rs_item{ .name = "TM25", .bag_category = TM_CATEGORY, .id = 0x139, .quantity = 0 },
 rs_item{ .name = "TM26", .bag_category = TM_CATEGORY, .id = 0x13a, .quantity = 0 },
 rs_item{ .name = "TM27", .bag_category = TM_CATEGORY, .id = 0x13b, .quantity = 0 },
 rs_item{ .name = "TM28", .bag_category = TM_CATEGORY, .id = 0x13c, .quantity = 0 },
 rs_item{ .name = "TM29", .bag_category = TM_CATEGORY, .id = 0x13d, .quantity = 0 },
 rs_item{ .name = "TM30", .bag_category = TM_CATEGORY, .id = 0x13e, .quantity = 0 },
 rs_item{ .name = "TM31", .bag_category = TM_CATEGORY, .id = 0x13f, .quantity = 0 },
 rs_item{ .name = "TM32", .bag_category = TM_CATEGORY, .id = 0x140, .quantity = 0 },
 rs_item{ .name = "TM33", .bag_category = TM_CATEGORY, .id = 0x141, .quantity = 0 },
 rs_item{ .name = "TM34", .bag_category = TM_CATEGORY, .id = 0x142, .quantity = 0 },
 rs_item{ .name = "TM35", .bag_category = TM_CATEGORY, .id = 0x143, .quantity = 0 },
 rs_item{ .name = "TM36", .bag_category = TM_CATEGORY, .id = 0x144, .quantity = 0 },
 rs_item{ .name = "TM37", .bag_category = TM_CATEGORY, .id = 0x145, .quantity = 0 },
 rs_item{ .name = "TM38", .bag_category = TM_CATEGORY, .id = 0x146, .quantity = 0 },
 rs_item{ .name = "TM39", .bag_category = TM_CATEGORY, .id = 0x147, .quantity = 0 },
 rs_item{ .name = "TM40", .bag_category = TM_CATEGORY, .id = 0x148, .quantity = 0 },
 rs_item{ .name = "TM41", .bag_category = TM_CATEGORY, .id = 0x149, .quantity = 0 },
 rs_item{ .name = "TM42", .bag_category = TM_CATEGORY, .id = 0x14a, .quantity = 0 },
 rs_item{ .name = "TM43", .bag_category = TM_CATEGORY, .id = 0x14b, .quantity = 0 },
 rs_item{ .name = "TM44", .bag_category = TM_CATEGORY, .id = 0x14d, .quantity = 0 },
 rs_item{ .name = "TM45", .bag_category = TM_CATEGORY, .id = 0x14d, .quantity = 0 },
 rs_item{ .name = "TM46", .bag_category = TM_CATEGORY, .id = 0x14e, .quantity = 0 },
 rs_item{ .name = "TM47", .bag_category = TM_CATEGORY, .id = 0x14f, .quantity = 0 },
 rs_item{ .name = "TM48", .bag_category = TM_CATEGORY, .id = 0x150, .quantity = 0 },
 rs_item{ .name = "TM49", .bag_category = TM_CATEGORY, .id = 0x151, .quantity = 0 },
 rs_item{ .name = "TM50", .bag_category = TM_CATEGORY, .id = 0x152, .quantity = 0 },
 rs_item{ .name = "HM01", .bag_category = TM_CATEGORY, .id = 0x153, .quantity = 0 },
 rs_item{ .name = "HM02", .bag_category = TM_CATEGORY, .id = 0x154, .quantity = 0 },
 rs_item{ .name = "HM03", .bag_category = TM_CATEGORY, .id = 0x155, .quantity = 0 },
 rs_item{ .name = "HM04", .bag_category = TM_CATEGORY, .id = 0x156, .quantity = 0 },
 rs_item{ .name = "HM05", .bag_category = TM_CATEGORY, .id = 0x157, .quantity = 0 },
 rs_item{ .name = "HM06", .bag_category = TM_CATEGORY, .id = 0x158, .quantity = 0 },
 rs_item{ .name = "HM07", .bag_category = TM_CATEGORY, .id = 0x159, .quantity = 0 },
 rs_item{ .name = "HM08", .bag_category = TM_CATEGORY, .id = 0x15a, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x15b, .quantity = 0 },
 rs_item{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x15c, .quantity = 0 },
};

