#include "util.h"

const char* pokemon_name_list[] = {
"?",
"Bulbasaur",
"Ivysaur",
"Venusaur",
"Charmander",
"Charmeleon",
"Charizard",
"Squirtle",
"Wartortle",
"Blastoise",
"Caterpie",
"Metapod",
"Butterfree",
"Weedle",
"Kakuna",
"Beedrill",
"Pidgey",
"Pidgeotto",
"Pidgeot",
"Rattata",
"Raticate",
"Spearow",
"Fearow",
"Ekans",
"Arbok",
"Pikachu",
"Raichu",
"Sandshrew",
"Sandslash",
"Nidoran♀",
"Nidorina",
"Nidoqueen",
"Nidoran♂",
"Nidorino",
"Nidoking",
"Clefairy",
"Clefable",
"Vulpix",
"Ninetales",
"Jigglypuff",
"Wigglytuff",
"Zubat",
"Golbat",
"Oddish",
"Gloom",
"Vileplume",
"Paras",
"Parasect",
"Venonat",
"Venomoth",
"Diglett",
"Dugtrio",
"Meowth",
"Persian",
"Psyduck",
"Golduck",
"Mankey",
"Primeape",
"Growlithe",
"Arcanine",
"Poliwag",
"Poliwhirl",
"Poliwrath",
"Abra",
"Kadabra",
"Alakazam",
"Machop",
"Machoke",
"Machamp",
"Bellsprout",
"Weepinbell",
"Victreebel",
"Tentacool",
"Tentacruel",
"Geodude",
"Graveler",
"Golem",
"Ponyta",
"Rapidash",
"Slowpoke",
"Slowbro",
"Magnemite",
"Magneton",
"Farfetch'd",
"Doduo",
"Dodrio",
"Seel",
"Dewgong",
"Grimer",
"Muk",
"Shellder",
"Cloyster",
"Gastly",
"Haunter",
"Gengar",
"Onix",
"Drowzee",
"Hypno",
"Krabby",
"Kingler",
"Voltorb",
"Electrode",
"Exeggcute",
"Exeggutor",
"Cubone",
"Marowak",
"Hitmonlee",
"Hitmonchan",
"Lickitung",
"Koffing",
"Weezing",
"Rhyhorn",
"Rhydon",
"Chansey",
"Tangela",
"Kangaskhan",
"Horsea",
"Seadra",
"Goldeen",
"Seaking",
"Staryu",
"Starmie",
"Mr.",
"Scyther",
"Jynx",
"Electabuzz",
"Magmar",
"Pinsir",
"Tauros",
"Magikarp",
"Gyarados",
"Lapras",
"Ditto",
"Eevee",
"Vaporeon",
"Jolteon",
"Flareon",
"Porygon",
"Omanyte",
"Omastar",
"Kabuto",
"Kabutops",
"Aerodactyl",
"Snorlax",
"Articuno",
"Zapdos",
"Moltres",
"Dratini",
"Dragonair",
"Dragonite",
"Mewtwo",
"Mew",
"Chikorita",
"Bayleef",
"Meganium",
"Cyndaquil",
"Quilava",
"Typhlosion",
"Totodile",
"Croconaw",
"Feraligatr",
"Sentret",
"Furret",
"Hoothoot",
"Noctowl",
"Ledyba",
"Ledian",
"Spinarak",
"Ariados",
"Crobat",
"Chinchou",
"Lanturn",
"Pichu",
"Cleffa",
"Igglybuff",
"Togepi",
"Togetic",
"Natu",
"Xatu",
"Mareep",
"Flaaffy",
"Ampharos",
"Bellossom",
"Marill",
"Azumarill",
"Sudowoodo",
"Politoed",
"Hoppip",
"Skiploom",
"Jumpluff",
"Aipom",
"Sunkern",
"Sunflora",
"Yanma",
"Wooper",
"Quagsire",
"Espeon",
"Umbreon",
"Murkrow",
"Slowking",
"Misdreavus",
"Unown",
"Wobbuffet",
"Girafarig",
"Pineco",
"Forretress",
"Dunsparce",
"Gligar",
"Steelix",
"Snubbull",
"Granbull",
"Qwilfish",
"Scizor",
"Shuckle",
"Heracross",
"Sneasel",
"Teddiursa",
"Ursaring",
"Slugma",
"Magcargo",
"Swinub",
"Piloswine",
"Corsola",
"Remoraid",
"Octillery",
"Delibird",
"Mantine",
"Skarmory",
"Houndour",
"Houndoom",
"Kingdra",
"Phanpy",
"Donphan",
"Porygon2",
"Stantler",
"Smeargle",
"Tyrogue",
"Hitmontop",
"Smoochum",
"Elekid",
"Magby",
"Miltank",
"Blissey",
"Raikou",
"Entei",
"Suicune",
"Larvitar",
"Pupitar",
"Tyranitar",
"Lugia",
"Ho-Oh",
"Celebi",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"?",
"Treecko",
"Grovyle",
"Sceptile",
"Torchic",
"Combusken",
"Blaziken",
"Mudkip",
"Marshtomp",
"Swampert",
"Poochyena",
"Mightyena",
"Zigzagoon",
"Linoone",
"Wurmple",
"Silcoon",
"Beautifly",
"Cascoon",
"Dustox",
"Lotad",
"Lombre",
"Ludicolo",
"Seedot",
"Nuzleaf",
"Shiftry",
"Nincada",
"Ninjask",
"Shedinja",
"Taillow",
"Swellow",
"Shroomish",
"Breloom",
"Spinda",
"Wingull",
"Pelipper",
"Surskit",
"Masquerain",
"Wailmer",
"Wailord",
"Skitty",
"Delcatty",
"Kecleon",
"Baltoy",
"Claydol",
"Nosepass",
"Torkoal",
"Sableye",
"Barboach",
"Whiscash",
"Luvdisc",
"Corphish",
"Crawdaunt",
"Feebas",
"Milotic",
"Carvanha",
"Sharpedo",
"Trapinch",
"Vibrava",
"Flygon",
"Makuhita",
"Hariyama",
"Electrike",
"Manectric",
"Numel",
"Camerupt",
"Spheal",
"Sealeo",
"Walrein",
"Cacnea",
"Cacturne",
"Snorunt",
"Glalie",
"Lunatone",
"Solrock",
"Azurill",
"Spoink",
"Grumpig",
"Plusle",
"Minun",
"Mawile",
"Meditite",
"Medicham",
"Swablu",
"Altaria",
"Wynaut",
"Duskull",
"Dusclops",
"Roselia",
"Slakoth",
"Vigoroth",
"Slaking",
"Gulpin",
"Swalot",
"Tropius",
"Whismur",
"Loudred",
"Exploud",
"Clamperl",
"Huntail",
"Gorebyss",
"Absol",
"Shuppet",
"Banette",
"Seviper",
"Zangoose",
"Relicanth",
"Aron",
"Lairon",
"Aggron",
"Castform",
"Volbeat",
"Illumise",
"Lileep",
"Cradily",
"Anorith",
"Armaldo",
"Ralts",
"Kirlia",
"Gardevoir",
"Bagon",
"Shelgon",
"Salamence",
"Beldum",
"Metang",
"Metagross",
"Regirock",
"Regice",
"Registeel",
"Kyogre",
"Groudon",
"Rayquaza",
"Latias",
"Latios",
"Jirachi",
"Deoxys",
"Chimecho",
"Pokémon",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"Unown",
"?",
};

extern const struct rs_item items_names_list[] = {
{ .name = "Nothing", .bag_category = BAD_CATEGORY, .id = 0x0 },
{ .name = "Master Ball", .bag_category = BALL_CATEGORY, .id = 0x1 },
{ .name = "Ultra Ball", .bag_category = BALL_CATEGORY, .id = 0x2 },
{ .name = "Great Ball", .bag_category = BALL_CATEGORY, .id = 0x3 },
{ .name = "Poké Ball", .bag_category = BALL_CATEGORY, .id = 0x4 },
{ .name = "Safari Ball", .bag_category = BALL_CATEGORY, .id = 0x5 },
{ .name = "Net Ball", .bag_category = BALL_CATEGORY, .id = 0x6 },
{ .name = "Dive Ball", .bag_category = BALL_CATEGORY, .id = 0x7 },
{ .name = "Nest Ball", .bag_category = BALL_CATEGORY, .id = 0x8 },
{ .name = "Repeat Ball", .bag_category = BALL_CATEGORY, .id = 0x9 },
{ .name = "Timer Ball", .bag_category = BALL_CATEGORY, .id = 0xa },
{ .name = "Luxury Ball", .bag_category = BALL_CATEGORY, .id = 0xb },
{ .name = "Premier Ball", .bag_category = BALL_CATEGORY, .id = 0xc },
{ .name = "Potion", .bag_category = ITEM_CATEGORY, .id = 0xd },
{ .name = "Antidote", .bag_category = ITEM_CATEGORY, .id = 0xe },
{ .name = "Burn Heal", .bag_category = ITEM_CATEGORY, .id = 0xf },
{ .name = "Ice Heal", .bag_category = ITEM_CATEGORY, .id = 0x10 },
{ .name = "Awakening", .bag_category = ITEM_CATEGORY, .id = 0x11 },
{ .name = "Parlyz Heal", .bag_category = ITEM_CATEGORY, .id = 0x12 },
{ .name = "Full Restore", .bag_category = ITEM_CATEGORY, .id = 0x13 },
{ .name = "Max Potion", .bag_category = ITEM_CATEGORY, .id = 0x14 },
{ .name = "Hyper Potion", .bag_category = ITEM_CATEGORY, .id = 0x15 },
{ .name = "Super Potion", .bag_category = ITEM_CATEGORY, .id = 0x16 },
{ .name = "Full Heal", .bag_category = ITEM_CATEGORY, .id = 0x17 },
{ .name = "Revive", .bag_category = ITEM_CATEGORY, .id = 0x18 },
{ .name = "Max Revive", .bag_category = ITEM_CATEGORY, .id = 0x19 },
{ .name = "Fresh Water", .bag_category = ITEM_CATEGORY, .id = 0x1a },
{ .name = "Soda Pop", .bag_category = ITEM_CATEGORY, .id = 0x1b },
{ .name = "Lemonade", .bag_category = ITEM_CATEGORY, .id = 0x1c },
{ .name = "Moomoo Milk", .bag_category = ITEM_CATEGORY, .id = 0x1d },
{ .name = "EnergyPowder", .bag_category = ITEM_CATEGORY, .id = 0x1e },
{ .name = "Energy Root", .bag_category = ITEM_CATEGORY, .id = 0x1f },
{ .name = "Heal Powder", .bag_category = ITEM_CATEGORY, .id = 0x20 },
{ .name = "Revival Herb", .bag_category = ITEM_CATEGORY, .id = 0x21 },
{ .name = "Ether", .bag_category = ITEM_CATEGORY, .id = 0x22 },
{ .name = "Max Ether", .bag_category = ITEM_CATEGORY, .id = 0x23 },
{ .name = "Elixir", .bag_category = ITEM_CATEGORY, .id = 0x24 },
{ .name = "Max Elixir", .bag_category = ITEM_CATEGORY, .id = 0x25 },
{ .name = "Lava Cookie", .bag_category = ITEM_CATEGORY, .id = 0x26 },
{ .name = "Blue Flute", .bag_category = ITEM_CATEGORY, .id = 0x27 },
{ .name = "Yellow Flute", .bag_category = ITEM_CATEGORY, .id = 0x28 },
{ .name = "Red Flute", .bag_category = ITEM_CATEGORY, .id = 0x29 },
{ .name = "Black Flute", .bag_category = ITEM_CATEGORY, .id = 0x2a },
{ .name = "White Flute", .bag_category = ITEM_CATEGORY, .id = 0x2b },
{ .name = "Berry Juice", .bag_category = ITEM_CATEGORY, .id = 0x2c },
{ .name = "Sacred Ash", .bag_category = ITEM_CATEGORY, .id = 0x2d },
{ .name = "Shoal Salt", .bag_category = ITEM_CATEGORY, .id = 0x2e },
{ .name = "Shoal Shell", .bag_category = ITEM_CATEGORY, .id = 0x2f },
{ .name = "Red Shard", .bag_category = ITEM_CATEGORY, .id = 0x30 },
{ .name = "Blue Shard", .bag_category = ITEM_CATEGORY, .id = 0x31 },
{ .name = "Yellow Shard", .bag_category = ITEM_CATEGORY, .id = 0x32 },
{ .name = "Green Shard", .bag_category = ITEM_CATEGORY, .id = 0x33 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x34 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x35 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x36 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x37 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x38 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x39 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3a },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3b },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3c },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3d },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x3e },
{ .name = "HP Up", .bag_category = ITEM_CATEGORY, .id = 0x3f },
{ .name = "Protein", .bag_category = ITEM_CATEGORY, .id = 0x40 },
{ .name = "Iron", .bag_category = ITEM_CATEGORY, .id = 0x41 },
{ .name = "Carbos", .bag_category = ITEM_CATEGORY, .id = 0x42 },
{ .name = "Calcium", .bag_category = ITEM_CATEGORY, .id = 0x43 },
{ .name = "Rare Candy", .bag_category = ITEM_CATEGORY, .id = 0x44 },
{ .name = "PP Up", .bag_category = ITEM_CATEGORY, .id = 0x45 },
{ .name = "Zinc", .bag_category = ITEM_CATEGORY, .id = 0x46 },
{ .name = "PP Max", .bag_category = ITEM_CATEGORY, .id = 0x47 },
{ .name = "unknown", .bag_category = ITEM_CATEGORY, .id = 0x48 },
{ .name = "Guard Spec.", .bag_category = ITEM_CATEGORY, .id = 0x49 },
{ .name = "Dire Hit", .bag_category = ITEM_CATEGORY, .id = 0x4a },
{ .name = "X Attack", .bag_category = ITEM_CATEGORY, .id = 0x4b },
{ .name = "X Defend", .bag_category = ITEM_CATEGORY, .id = 0x4c },
{ .name = "X Speed", .bag_category = ITEM_CATEGORY, .id = 0x4d },
{ .name = "X Accuracy", .bag_category = ITEM_CATEGORY, .id = 0x4e },
{ .name = "X Special", .bag_category = ITEM_CATEGORY, .id = 0x4f },
{ .name = "Poké Doll", .bag_category = ITEM_CATEGORY, .id = 0x50 },
{ .name = "Fluffy Tail", .bag_category = ITEM_CATEGORY, .id = 0x51 },
{ .name = "unknown", .bag_category = ITEM_CATEGORY, .id = 0x52 },
{ .name = "Super Repel", .bag_category = ITEM_CATEGORY, .id = 0x53 },
{ .name = "Max Repel", .bag_category = ITEM_CATEGORY, .id = 0x54 },
{ .name = "Escape Rope", .bag_category = ITEM_CATEGORY, .id = 0x55 },
{ .name = "Repel", .bag_category = ITEM_CATEGORY, .id = 0x56 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x57 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x58 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x59 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x5a },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x5b },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x5c },
{ .name = "Sun Stone", .bag_category = ITEM_CATEGORY, .id = 0x5d },
{ .name = "Moon Stone", .bag_category = ITEM_CATEGORY, .id = 0x5e },
{ .name = "Fire Stone", .bag_category = ITEM_CATEGORY, .id = 0x5f },
{ .name = "Thunderstone", .bag_category = ITEM_CATEGORY, .id = 0x60 },
{ .name = "Water Stone", .bag_category = ITEM_CATEGORY, .id = 0x61 },
{ .name = "Leaf Stone", .bag_category = ITEM_CATEGORY, .id = 0x62 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x63 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x64 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x65 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x66 },
{ .name = "TinyMushroom", .bag_category = ITEM_CATEGORY, .id = 0x67 },
{ .name = "Big Mushroom", .bag_category = ITEM_CATEGORY, .id = 0x68 },
{ .name = "unknown", .bag_category = ITEM_CATEGORY, .id = 0x69 },
{ .name = "Pearl", .bag_category = ITEM_CATEGORY, .id = 0x6a },
{ .name = "Big Pearl", .bag_category = ITEM_CATEGORY, .id = 0x6b },
{ .name = "Stardust", .bag_category = ITEM_CATEGORY, .id = 0x6c },
{ .name = "Star Piece", .bag_category = ITEM_CATEGORY, .id = 0x6d },
{ .name = "Nugget", .bag_category = ITEM_CATEGORY, .id = 0x6e },
{ .name = "Heart Scale", .bag_category = ITEM_CATEGORY, .id = 0x6f },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x70 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x71 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x72 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x73 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x74 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x75 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x76 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x77 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x78 },
{ .name = "Orange Mail", .bag_category = ITEM_CATEGORY, .id = 0x79 },
{ .name = "Harbor Mail", .bag_category = ITEM_CATEGORY, .id = 0x7a },
{ .name = "Glitter Mail", .bag_category = ITEM_CATEGORY, .id = 0x7b },
{ .name = "Mech Mail", .bag_category = ITEM_CATEGORY, .id = 0x7c },
{ .name = "Wood Mail", .bag_category = ITEM_CATEGORY, .id = 0x7d },
{ .name = "Wave Mail", .bag_category = ITEM_CATEGORY, .id = 0x7e },
{ .name = "Bead Mail", .bag_category = ITEM_CATEGORY, .id = 0x7f },
{ .name = "Shadow Mail", .bag_category = ITEM_CATEGORY, .id = 0x80 },
{ .name = "Tropic Mail", .bag_category = ITEM_CATEGORY, .id = 0x81 },
{ .name = "Dream Mail", .bag_category = ITEM_CATEGORY, .id = 0x82 },
{ .name = "Fab Mail", .bag_category = ITEM_CATEGORY, .id = 0x83 },
{ .name = "Retro Mail", .bag_category = ITEM_CATEGORY, .id = 0x84 },
{ .name = "Cheri Berry", .bag_category = BERRY_CATEGORY, .id = 0x85 },
{ .name = "Chesto Berry", .bag_category = BERRY_CATEGORY, .id = 0x86 },
{ .name = "Pecha Berry", .bag_category = BERRY_CATEGORY, .id = 0x87 },
{ .name = "Rawst Berry", .bag_category = BERRY_CATEGORY, .id = 0x88 },
{ .name = "Aspear Berry", .bag_category = BERRY_CATEGORY, .id = 0x89 },
{ .name = "Leppa Berry", .bag_category = BERRY_CATEGORY, .id = 0x8a },
{ .name = "Oran Berry", .bag_category = BERRY_CATEGORY, .id = 0x8b },
{ .name = "Persim Berry", .bag_category = BERRY_CATEGORY, .id = 0x8c },
{ .name = "Lum Berry", .bag_category = BERRY_CATEGORY, .id = 0x8d },
{ .name = "Sitrus Berry", .bag_category = BERRY_CATEGORY, .id = 0x8e },
{ .name = "Figy Berry", .bag_category = BERRY_CATEGORY, .id = 0x8f },
{ .name = "Wiki Berry", .bag_category = BERRY_CATEGORY, .id = 0x90 },
{ .name = "Mago Berry", .bag_category = BERRY_CATEGORY, .id = 0x91 },
{ .name = "Aguav Berry", .bag_category = BERRY_CATEGORY, .id = 0x92 },
{ .name = "Iapapa Berry", .bag_category = BERRY_CATEGORY, .id = 0x93 },
{ .name = "Razz Berry", .bag_category = BERRY_CATEGORY, .id = 0x94 },
{ .name = "Bluk Berry", .bag_category = BERRY_CATEGORY, .id = 0x95 },
{ .name = "Nanab Berry", .bag_category = BERRY_CATEGORY, .id = 0x96 },
{ .name = "Wepear Berry", .bag_category = BERRY_CATEGORY, .id = 0x97 },
{ .name = "Pinap Berry", .bag_category = BERRY_CATEGORY, .id = 0x98 },
{ .name = "Pomeg Berry", .bag_category = BERRY_CATEGORY, .id = 0x99 },
{ .name = "Kelpsy Berry", .bag_category = BERRY_CATEGORY, .id = 0x9a },
{ .name = "Qualot Berry", .bag_category = BERRY_CATEGORY, .id = 0x9b },
{ .name = "Hondew Berry", .bag_category = BERRY_CATEGORY, .id = 0x9c },
{ .name = "Grepa Berry", .bag_category = BERRY_CATEGORY, .id = 0x9d },
{ .name = "Tamato Berry", .bag_category = BERRY_CATEGORY, .id = 0x9e },
{ .name = "Cornn Berry", .bag_category = BERRY_CATEGORY, .id = 0x9f },
{ .name = "Magost Berry", .bag_category = BERRY_CATEGORY, .id = 0xa0 },
{ .name = "Rabuta Berry", .bag_category = BERRY_CATEGORY, .id = 0xa1 },
{ .name = "Nomel Berry", .bag_category = BERRY_CATEGORY, .id = 0xa2 },
{ .name = "Spelon Berry", .bag_category = BERRY_CATEGORY, .id = 0xa3 },
{ .name = "Pamtre Berry", .bag_category = BERRY_CATEGORY, .id = 0xa4 },
{ .name = "Watmel Berry", .bag_category = BERRY_CATEGORY, .id = 0xa5 },
{ .name = "Durin Berry", .bag_category = BERRY_CATEGORY, .id = 0xa6 },
{ .name = "Belue Berry", .bag_category = BERRY_CATEGORY, .id = 0xa7 },
{ .name = "Liechi Berry", .bag_category = BERRY_CATEGORY, .id = 0xa8 },
{ .name = "Ganlon Berry", .bag_category = BERRY_CATEGORY, .id = 0xa9 },
{ .name = "Salac Berry", .bag_category = BERRY_CATEGORY, .id = 0xaa },
{ .name = "Petaya Berry", .bag_category = BERRY_CATEGORY, .id = 0xab },
{ .name = "Apicot Berry", .bag_category = BERRY_CATEGORY, .id = 0xac },
{ .name = "Lansat Berry", .bag_category = BERRY_CATEGORY, .id = 0xad },
{ .name = "Starf Berry", .bag_category = BERRY_CATEGORY, .id = 0xae },
{ .name = "Enigma Berry", .bag_category = BERRY_CATEGORY, .id = 0xaf },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xb0 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xb1 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xb2 },
{ .name = "BrightPowder", .bag_category = ITEM_CATEGORY, .id = 0xb3 },
{ .name = "White Herb", .bag_category = ITEM_CATEGORY, .id = 0xb4 },
{ .name = "Macho Brace", .bag_category = ITEM_CATEGORY, .id = 0xb5 },
{ .name = "Exp. Share", .bag_category = ITEM_CATEGORY, .id = 0xb6 },
{ .name = "Quick Claw", .bag_category = ITEM_CATEGORY, .id = 0xb7 },
{ .name = "Soothe Bell", .bag_category = ITEM_CATEGORY, .id = 0xb8 },
{ .name = "Mental Herb", .bag_category = ITEM_CATEGORY, .id = 0xb9 },
{ .name = "Choice Band", .bag_category = ITEM_CATEGORY, .id = 0xba },
{ .name = "King's Rock", .bag_category = ITEM_CATEGORY, .id = 0xbb },
{ .name = "SilverPowder", .bag_category = ITEM_CATEGORY, .id = 0xbc },
{ .name = "Amulet Coin", .bag_category = ITEM_CATEGORY, .id = 0xbd },
{ .name = "Cleanse Tag", .bag_category = ITEM_CATEGORY, .id = 0xbe },
{ .name = "Soul Dew", .bag_category = ITEM_CATEGORY, .id = 0xbf },
{ .name = "DeepSeaTooth", .bag_category = ITEM_CATEGORY, .id = 0xc0 },
{ .name = "DeepSeaScale", .bag_category = ITEM_CATEGORY, .id = 0xc1 },
{ .name = "Smoke Ball", .bag_category = ITEM_CATEGORY, .id = 0xc2 },
{ .name = "Everstone", .bag_category = ITEM_CATEGORY, .id = 0xc3 },
{ .name = "Focus Band", .bag_category = ITEM_CATEGORY, .id = 0xc4 },
{ .name = "Lucky Egg", .bag_category = ITEM_CATEGORY, .id = 0xc5 },
{ .name = "Scope Lens", .bag_category = ITEM_CATEGORY, .id = 0xc6 },
{ .name = "Metal Coat", .bag_category = ITEM_CATEGORY, .id = 0xc7 },
{ .name = "Leftovers", .bag_category = ITEM_CATEGORY, .id = 0xc8 },
{ .name = "Dragon Scale", .bag_category = ITEM_CATEGORY, .id = 0xc9 },
{ .name = "Light Ball", .bag_category = ITEM_CATEGORY, .id = 0xca },
{ .name = "Soft Sand", .bag_category = ITEM_CATEGORY, .id = 0xcb },
{ .name = "Hard Stone", .bag_category = ITEM_CATEGORY, .id = 0xcc },
{ .name = "Miracle Seed", .bag_category = ITEM_CATEGORY, .id = 0xcd },
{ .name = "BlackGlasses", .bag_category = ITEM_CATEGORY, .id = 0xce },
{ .name = "Black Belt", .bag_category = ITEM_CATEGORY, .id = 0xcf },
{ .name = "Magnet", .bag_category = ITEM_CATEGORY, .id = 0xd0 },
{ .name = "Mystic Water", .bag_category = ITEM_CATEGORY, .id = 0xd1 },
{ .name = "Sharp Beak", .bag_category = ITEM_CATEGORY, .id = 0xd2 },
{ .name = "Poison Barb", .bag_category = ITEM_CATEGORY, .id = 0xd3 },
{ .name = "NeverMeltIce", .bag_category = ITEM_CATEGORY, .id = 0xd4 },
{ .name = "Spell Tag", .bag_category = ITEM_CATEGORY, .id = 0xd5 },
{ .name = "TwistedSpoon", .bag_category = ITEM_CATEGORY, .id = 0xd6 },
{ .name = "Charcoal", .bag_category = ITEM_CATEGORY, .id = 0xd7 },
{ .name = "Dragon Fang", .bag_category = ITEM_CATEGORY, .id = 0xd8 },
{ .name = "Silk Scarf", .bag_category = ITEM_CATEGORY, .id = 0xd9 },
{ .name = "Up-Grade", .bag_category = ITEM_CATEGORY, .id = 0xda },
{ .name = "Shell Bell", .bag_category = ITEM_CATEGORY, .id = 0xdb },
{ .name = "Sea Incense", .bag_category = ITEM_CATEGORY, .id = 0xdc },
{ .name = "Lax Incense", .bag_category = ITEM_CATEGORY, .id = 0xdd },
{ .name = "Lucky Punch", .bag_category = ITEM_CATEGORY, .id = 0xde },
{ .name = "Metal Powder", .bag_category = ITEM_CATEGORY, .id = 0xdf },
{ .name = "Thick Club", .bag_category = ITEM_CATEGORY, .id = 0xe0 },
{ .name = "Stick", .bag_category = ITEM_CATEGORY, .id = 0xe1 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe2 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe3 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe4 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe5 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe6 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe7 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe8 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xe9 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xea },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xeb },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xec },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xed },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xee },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xef },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf0 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf1 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf2 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf3 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf4 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf5 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf6 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf7 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf8 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xf9 },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfa },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfb },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfc },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0xfd },
{ .name = "Red Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0xfe },
{ .name = "Blue Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0xff },
{ .name = "Pink Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0x100 },
{ .name = "Green Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0x101 },
{ .name = "Yellow Scarf", .bag_category = KEY_ITEM_CATEGORY, .id = 0x102 },
{ .name = "Mach Bike", .bag_category = KEY_ITEM_CATEGORY, .id = 0x103 },
{ .name = "Coin Case", .bag_category = KEY_ITEM_CATEGORY, .id = 0x104 },
{ .name = "Itemfinder", .bag_category = KEY_ITEM_CATEGORY, .id = 0x105 },
{ .name = "Old Rod", .bag_category = KEY_ITEM_CATEGORY, .id = 0x106 },
{ .name = "Good Rod", .bag_category = KEY_ITEM_CATEGORY, .id = 0x107 },
{ .name = "Super Rod", .bag_category = KEY_ITEM_CATEGORY, .id = 0x108 },
{ .name = "S.S. Ticket", .bag_category = KEY_ITEM_CATEGORY, .id = 0x109 },
{ .name = "Contest Pass", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10a },
{ .name = "unknown", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10b },
{ .name = "Wailmer Pail", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10c },
{ .name = "Devon Goods", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10d },
{ .name = "Soot Sack", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10e },
{ .name = "Basement Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x10f },
{ .name = "Acro Bike", .bag_category = KEY_ITEM_CATEGORY, .id = 0x110 },
{ .name = "Pokéblock Case", .bag_category = KEY_ITEM_CATEGORY, .id = 0x111 },
{ .name = "Letter", .bag_category = KEY_ITEM_CATEGORY, .id = 0x112 },
{ .name = "Eon Ticket", .bag_category = KEY_ITEM_CATEGORY, .id = 0x113 },
{ .name = "Red Orb", .bag_category = KEY_ITEM_CATEGORY, .id = 0x114 },
{ .name = "Blue Orb", .bag_category = KEY_ITEM_CATEGORY, .id = 0x115 },
{ .name = "Scanner", .bag_category = KEY_ITEM_CATEGORY, .id = 0x116 },
{ .name = "Go-Goggles", .bag_category = KEY_ITEM_CATEGORY, .id = 0x117 },
{ .name = "Meteorite", .bag_category = KEY_ITEM_CATEGORY, .id = 0x118 },
{ .name = "Rm. 1 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x119 },
{ .name = "Rm. 2 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11a },
{ .name = "Rm. 4 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11b },
{ .name = "Rm. 6 Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11c },
{ .name = "Storage Key", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11d },
{ .name = "Root Fossil", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11e },
{ .name = "Claw Fossil", .bag_category = KEY_ITEM_CATEGORY, .id = 0x11f },
{ .name = "Devon Scope", .bag_category = KEY_ITEM_CATEGORY, .id = 0x120 },
{ .name = "TM01", .bag_category = TM_CATEGORY, .id = 0x121 },
{ .name = "TM02", .bag_category = TM_CATEGORY, .id = 0x122 },
{ .name = "TM03", .bag_category = TM_CATEGORY, .id = 0x123 },
{ .name = "TM04", .bag_category = TM_CATEGORY, .id = 0x124 },
{ .name = "TM05", .bag_category = TM_CATEGORY, .id = 0x125 },
{ .name = "TM06", .bag_category = TM_CATEGORY, .id = 0x126 },
{ .name = "TM07", .bag_category = TM_CATEGORY, .id = 0x127 },
{ .name = "TM08", .bag_category = TM_CATEGORY, .id = 0x128 },
{ .name = "TM09", .bag_category = TM_CATEGORY, .id = 0x129 },
{ .name = "TM10", .bag_category = TM_CATEGORY, .id = 0x12a },
{ .name = "TM11", .bag_category = TM_CATEGORY, .id = 0x12b },
{ .name = "TM12", .bag_category = TM_CATEGORY, .id = 0x12c },
{ .name = "TM13", .bag_category = TM_CATEGORY, .id = 0x12d },
{ .name = "TM14", .bag_category = TM_CATEGORY, .id = 0x12e },
{ .name = "TM15", .bag_category = TM_CATEGORY, .id = 0x12f },
{ .name = "TM16", .bag_category = TM_CATEGORY, .id = 0x130 },
{ .name = "TM17", .bag_category = TM_CATEGORY, .id = 0x131 },
{ .name = "TM18", .bag_category = TM_CATEGORY, .id = 0x132 },
{ .name = "TM19", .bag_category = TM_CATEGORY, .id = 0x133 },
{ .name = "TM20", .bag_category = TM_CATEGORY, .id = 0x134 },
{ .name = "TM21", .bag_category = TM_CATEGORY, .id = 0x135 },
{ .name = "TM22", .bag_category = TM_CATEGORY, .id = 0x136 },
{ .name = "TM23", .bag_category = TM_CATEGORY, .id = 0x137 },
{ .name = "TM24", .bag_category = TM_CATEGORY, .id = 0x138 },
{ .name = "TM25", .bag_category = TM_CATEGORY, .id = 0x139 },
{ .name = "TM26", .bag_category = TM_CATEGORY, .id = 0x13a },
{ .name = "TM27", .bag_category = TM_CATEGORY, .id = 0x13b },
{ .name = "TM28", .bag_category = TM_CATEGORY, .id = 0x13c },
{ .name = "TM29", .bag_category = TM_CATEGORY, .id = 0x13d },
{ .name = "TM30", .bag_category = TM_CATEGORY, .id = 0x13e },
{ .name = "TM31", .bag_category = TM_CATEGORY, .id = 0x13f },
{ .name = "TM32", .bag_category = TM_CATEGORY, .id = 0x140 },
{ .name = "TM33", .bag_category = TM_CATEGORY, .id = 0x141 },
{ .name = "TM34", .bag_category = TM_CATEGORY, .id = 0x142 },
{ .name = "TM35", .bag_category = TM_CATEGORY, .id = 0x143 },
{ .name = "TM36", .bag_category = TM_CATEGORY, .id = 0x144 },
{ .name = "TM37", .bag_category = TM_CATEGORY, .id = 0x145 },
{ .name = "TM38", .bag_category = TM_CATEGORY, .id = 0x146 },
{ .name = "TM39", .bag_category = TM_CATEGORY, .id = 0x147 },
{ .name = "TM40", .bag_category = TM_CATEGORY, .id = 0x148 },
{ .name = "TM41", .bag_category = TM_CATEGORY, .id = 0x149 },
{ .name = "TM42", .bag_category = TM_CATEGORY, .id = 0x14a },
{ .name = "TM43", .bag_category = TM_CATEGORY, .id = 0x14b },
{ .name = "TM44", .bag_category = TM_CATEGORY, .id = 0x14c },
{ .name = "TM45", .bag_category = TM_CATEGORY, .id = 0x14d },
{ .name = "TM46", .bag_category = TM_CATEGORY, .id = 0x14e },
{ .name = "TM47", .bag_category = TM_CATEGORY, .id = 0x14f },
{ .name = "TM48", .bag_category = TM_CATEGORY, .id = 0x150 },
{ .name = "TM49", .bag_category = TM_CATEGORY, .id = 0x151 },
{ .name = "TM50", .bag_category = TM_CATEGORY, .id = 0x152 },
{ .name = "HM01", .bag_category = TM_CATEGORY, .id = 0x153 },
{ .name = "HM02", .bag_category = TM_CATEGORY, .id = 0x154 },
{ .name = "HM03", .bag_category = TM_CATEGORY, .id = 0x155 },
{ .name = "HM04", .bag_category = TM_CATEGORY, .id = 0x156 },
{ .name = "HM05", .bag_category = TM_CATEGORY, .id = 0x157 },
{ .name = "HM06", .bag_category = TM_CATEGORY, .id = 0x158 },
{ .name = "HM07", .bag_category = TM_CATEGORY, .id = 0x159 },
{ .name = "HM08", .bag_category = TM_CATEGORY, .id = 0x15a },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x15b },
{ .name = "unknown", .bag_category = BAD_CATEGORY, .id = 0x15c },
};

const int items_size = sizeof(items_names_list);
